image: docker:latest
variables:
  IMAGE_NAME: "r-base-dev"
services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$IMAGE_NAME" -f $IMAGE_NAME/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME"
