.docker-template: &docker
  tags:
    - linux
  image: docker
  services:
  - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$IMAGE_NAME" -f $IMAGE_FAMILY_NAME/$IMAGE_NAME .
    - docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME"

r-devel-minimal:
  variables:
    IMAGE_FAMILY_NAME: "r-devel"
    IMAGE_NAME: "r-devel-minimal"
  <<: *docker

r-devel:
  variables:
    IMAGE_FAMILY_NAME: "r-devel"
    IMAGE_NAME: "r-devel"
  needs:
    - r-devel-minimal
  <<: *docker

