image: docker:latest
services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo $
    - docker build --pull -t "$CI_REGISTRY_IMAGE/r-memprof:$CI_COMMIT_REF_NAME" -f r-memprof/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/r-memprof:$CI_COMMIT_REF_NAME"
