.docker-template: &docker
  stage: deploy
  tags:
    - linux
  image: docker
  services:
  - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$IMAGE_NAME" -f $IMAGE_NAME/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME"

docker-r-base-dev:
  variables:
    IMAGE_NAME: "r-base-dev"
  <<: *docker

docker-r-devel:
  variables:
    IMAGE_NAME: "r-devel"
  <<: *docker

docker-r-3.1.0:
  variables:
    IMAGE_NAME: "r-3.1.0"
  <<: *docker
